services:
  mongodb:
    image: mongo
    container_name: BlogMongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: weLoveMongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init:/data/init
      - ./init/pics:/data/pics
    networks:
      - internalnet
  
  frontend:
    container_name: nginx_container_blog
    build: ./frontend
    image: nginx_image
    ports:
      - "4200:80"
    networks:
      - internalnet
  
  backend:
    container_name: blog_backend
    build: ./backend
    environment:
      MONGO_URI: "mongodb://admin:weLoveMongo@mongodb:27017/Blog?authSource=admin"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - internalnet

volumes:
  data:

networks:
  internalnet:
    driver: bridge