services:
  mongodb:
    image: mongo
    container_name: BlogMongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: weLoveMongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init:/data/init
      - ./init/pics:/data/pics
    networks:
      - internalnet
  
  frontend:
    container_name: nginx_container_blog
    build: ./frontend
    image: nginx_image
    ports:
      - "4200:80"
    networks:
      - internalnet

  backend:
    build: ./backend
    container_name: BlogBackend
    environment:
      APP_NAME: Blog
      PORT: 4000
      DB_URI: mongodb://admin:weLoveMongo@mongodb:27017/Blog
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - internalnet

volumes:
  mongodb_data:

networks:
  internalnet:
    driver: bridge